default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: stargazing_development

test:
  <<: *default
  database: stargazing_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
